workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
    environment:
      flutter: stable
      groups:
        - SECRET
    scripts:
      - echo "Installing jq..."
      - which jq || (brew install jq || sudo apt-get update && sudo apt-get install -y jq || npm install -g jq)
      - flutter build apk --release --dart-define=ENVIRONMENT=production
      - bash upload_apk_new.sh
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
